<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OBP.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.85" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/OBP.Composition/OBP.Composition.csproj" />
    <ProjectReference Include="../../src/OBP.Core/OBP.Core.csproj" />
    <ProjectReference Include="../../src/OBP.IO/OBP.IO.csproj" />
    <ProjectReference Include="../../src/OBP.PS2/OBP.PS2.csproj" />
    <ProjectReference Include="../../src/OBP.RAC1/OBP.RAC1.csproj" />
    <ProjectReference Include="../../src/OBP.RAC2/OBP.RAC2.csproj" />
    <ProjectReference Include="../../src/OBP.RAC3/OBP.RAC3.csproj" />
    <ProjectReference Include="../../src/OBP.Runtime/OBP.Runtime.csproj" />
  </ItemGroup>

</Project>
