<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OBP.PS2.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../OBP.PS2/OBP.PS2.csproj" />
    <ProjectReference Include="../OBP.Runtime/OBP.Runtime.csproj" />
  </ItemGroup>

</Project>
